stages:
  - building
  - running

gcc:
  stage: building
  script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles"
      -DCMAKE_C_COMPILER=gcc
      -DCMAKE_CXX_COMPILER=g++
      -DCMAKE_BUILD_TYPE=Release
      ..
    - cmake --build .

clang:
  stage: building
  script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles"
      -DCMAKE_C_COMPILER=clang
      -DCMAKE_CXX_COMPILER=clang++
      -DCMAKE_BUILD_TYPE=Release
      ..
    - cmake --build .

docker:
  stage: building
  script:
    - docker build -t docker_example:latest .

docker-gcc:
  stage: running
  script:
    - docker run --rm docker_example